= Serenity (3) for Spring Boot (2) using Cucumber

This PoC is heavily based on the official https://github.com/serenity-bdd/serenity-cucumber-starter[Serenity BDD and Cucumber starter] combined with the https://serenity-bdd.github.io/docs/tutorials/cucumber-screenplay[Serenity Cucumber tutorial]
and the https://serenity-bdd.github.io/docs/screenplay/screenplay_rest[Serenity Screenplay with REST APIs tutorial].

Current stack:

* Serenity BDD 3.4.3
** Cucumber 7.8.1
** RestAssured 5.2.1
* Spring Boot 3.0.0
** JUnit (Vintage) 5.9.1

== Running the tests under Maven

This project comes with just a Maven build script. To run the tests, open a command window and run:

----
mvn clean verify
----

== Viewing the reports

The command provided above will produce a Serenity test report in the `target/site/serenity` directory. Go take a look!

== Some problems encountered during the development of this configuration
All problems encountered for getting this stack to work under Spring boot 2.7.x seemed to have cleared.

This has greatly simplified the POM contents, as all workarounds could be removed after moving to Spring Boot 3.0.0.
